# Generated by Django 5.0.6 on 2024-06-28 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_tracker.company'),
        ),
        migrations.AddField(
            model_name='job',
            name='date_applied',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_tracker.hiringmanager'),
        ),
    ]
