# Generated by Django 5.0.6 on 2024-06-28 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0002_job_company_job_date_applied_job_hiring_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job_tracker.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='hiring_manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job_tracker.hiringmanager'),
        ),
    ]
