# Generated by Django 5.0.6 on 2024-06-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0003_alter_job_company_alter_job_hiring_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_applied',
            field=models.DateField(default=None),
        ),
    ]
