name: Build and share Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-share:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Use a stable version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action  # Default to the latest stable version

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0  # Use a stable version
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print tags
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:latest

      - name: Build and push
        uses: docker/build-push-action@v2.8.0  # Use a stable version
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:latest
