name: Build and share Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-share:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0  # Updated for Node.js 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.0  # Updated for Node.js 20

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0  # Updated for Node.js 20
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print tags
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:latest

      - name: Build and push
        uses: docker/build-push-action@v4.2.0  # Updated for Node.js 20
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:latest
